name: huntly
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_test:
    image: postgres:18
    environment:
      POSTGRES_DB: ${TEST_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DATABASE_NAME}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

    volumes:
      - .:/app
      - /app/.venv

  backend_test:
    build: .
    depends_on:
      db_test:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_test:5432/${TEST_DATABASE_NAME}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

    command: >
      sh -c " uv run alembic upgrade head && uv run pytest -v"

volumes:
  postgres_data:
