"""add model column comments

Revision ID: 6ba2d65b164c
Revises: bb99e7312ea9
Create Date: 2026-07-29 13:57:35.079282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ba2d65b164c'
down_revision: Union[str, Sequence[str], None] = 'bb99e7312ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_status_history', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID generated in the app via uuid4)',
               existing_comment='Primary key',
               existing_nullable=False)
    op.alter_column('application_status_history', 'application_id',
               existing_type=sa.UUID(),
               comment='FK to job_applications.id; application this status event belongs to',
               existing_nullable=False)
    op.alter_column('application_status_history', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='Pipeline status at this history event (ApplicationStatus enum value)',
               existing_comment='Status recorded at this history point',
               existing_nullable=False)
    op.alter_column('application_status_history', 'notes',
               existing_type=sa.TEXT(),
               comment='Optional context for this status change (rejection reason, etc.)',
               existing_comment='Optional notes for this status change',
               existing_nullable=True)
    op.alter_column('application_status_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was first created (DB server default, timezone-aware)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('application_status_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was last updated (server default + ORM onupdate)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID generated in the app via uuid4)',
               existing_comment='Primary key',
               existing_nullable=False)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Company display name (unique across the tracker)',
               existing_comment='Company display name',
               existing_nullable=False)
    op.alter_column('companies', 'website',
               existing_type=sa.VARCHAR(length=255),
               comment='Company website URL; unique when set',
               existing_comment='Company website URL',
               existing_nullable=True)
    op.alter_column('companies', 'linkedin_url',
               existing_type=sa.VARCHAR(length=255),
               comment='Company LinkedIn page URL; unique when set',
               existing_comment='Company LinkedIn URL',
               existing_nullable=True)
    op.alter_column('companies', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment='Headquarters or primary company location',
               existing_comment='HQ or primary location',
               existing_nullable=True)
    op.alter_column('companies', 'notes',
               existing_type=sa.TEXT(),
               comment='Free-form notes about the company (culture, referrals, etc.)',
               existing_comment='Free-form notes about the company',
               existing_nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was first created (DB server default, timezone-aware)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was last updated (server default + ORM onupdate)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contacts', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID generated in the app via uuid4)',
               existing_nullable=False)
    op.alter_column('contacts', 'company_id',
               existing_type=sa.UUID(),
               comment='FK to companies.id; company this person works at / represents',
               existing_nullable=False)
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Contact full name',
               existing_nullable=False)
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.VARCHAR(length=32),
               comment='Phone number (E.164-ish room); unique when set',
               existing_nullable=True)
    op.alter_column('contacts', 'role',
               existing_type=sa.VARCHAR(length=255),
               comment='Job title or relationship (e.g. Recruiter, Eng Manager)',
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address; unique when set',
               existing_nullable=True)
    op.alter_column('contacts', 'linkedin_url',
               existing_type=sa.VARCHAR(length=255),
               comment='Personal LinkedIn profile URL; unique when set',
               existing_nullable=True)
    op.alter_column('contacts', 'notes',
               existing_type=sa.TEXT(),
               comment='Free-form notes (last conversation, intro path, etc.)',
               existing_nullable=True)
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was first created (DB server default, timezone-aware)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was last updated (server default + ORM onupdate)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('interviews', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID generated in the app via uuid4)',
               existing_nullable=False)
    op.alter_column('interviews', 'application_id',
               existing_type=sa.UUID(),
               comment='FK to job_applications.id; application this interview belongs to',
               existing_nullable=False)
    op.alter_column('interviews', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Interview start time (timezone-aware)',
               existing_nullable=False)
    op.alter_column('interviews', 'interview_type',
               existing_type=sa.VARCHAR(length=32),
               comment='Interview format/focus (InterviewType enum value, e.g. video)',
               existing_nullable=False)
    op.alter_column('interviews', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment='Physical location or office name for onsite interviews',
               existing_nullable=True)
    op.alter_column('interviews', 'url_link',
               existing_type=sa.VARCHAR(length=512),
               comment='Video call or portal URL for remote interviews',
               existing_nullable=True)
    op.alter_column('interviews', 'notes',
               existing_type=sa.TEXT(),
               comment='Prep notes, interviewer names, takeaways, etc.',
               existing_nullable=True)
    op.alter_column('interviews', 'outcome',
               existing_type=sa.VARCHAR(length=32),
               comment='Result of this interview only (InterviewOutcome enum value)',
               existing_nullable=True)
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was first created (DB server default, timezone-aware)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('interviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was last updated (server default + ORM onupdate)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_applications', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID generated in the app via uuid4)',
               existing_comment='Primary key',
               existing_nullable=False)
    op.alter_column('job_applications', 'company_id',
               existing_type=sa.UUID(),
               comment='FK to companies.id; exactly one company owns this application',
               existing_comment='Owning company (exactly one per application)',
               existing_nullable=False)
    op.alter_column('job_applications', 'job_title',
               existing_type=sa.VARCHAR(length=255),
               comment='Role title (unique per company via composite constraint)',
               existing_nullable=False)
    op.alter_column('job_applications', 'job_description',
               existing_type=sa.TEXT(),
               comment='Full or pasted job description text',
               existing_nullable=True)
    op.alter_column('job_applications', 'job_url',
               existing_type=sa.VARCHAR(length=512),
               comment='Canonical job posting URL; unique when set',
               existing_nullable=True)
    op.alter_column('job_applications', 'job_type',
               existing_type=sa.VARCHAR(length=32),
               comment='Employment type (JobType enum value, e.g. full_time)',
               existing_nullable=False)
    op.alter_column('job_applications', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment='Job location or remote label (not unique — many jobs share cities)',
               existing_nullable=True)
    op.alter_column('job_applications', 'salary_min',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Lower bound of expected or listed pay (Numeric 12,2)',
               existing_nullable=True)
    op.alter_column('job_applications', 'salary_max',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Upper bound of expected or listed pay (Numeric 12,2)',
               existing_nullable=True)
    op.alter_column('job_applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When you submitted the application; null if still a wishlist item',
               existing_nullable=True)
    op.alter_column('job_applications', 'priority',
               existing_type=sa.VARCHAR(length=16),
               comment='Personal priority in the tracker (Priority enum value)',
               existing_nullable=True)
    op.alter_column('job_applications', 'notes',
               existing_type=sa.TEXT(),
               comment='Free-form notes for this application',
               existing_nullable=True)
    op.alter_column('job_applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was first created (DB server default, timezone-aware)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was last updated (server default + ORM onupdate)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was last updated (server default + ORM onupdate)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was first created (DB server default, timezone-aware)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_applications', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Free-form notes for this application',
               existing_nullable=True)
    op.alter_column('job_applications', 'priority',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='Personal priority in the tracker (Priority enum value)',
               existing_nullable=True)
    op.alter_column('job_applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When you submitted the application; null if still a wishlist item',
               existing_nullable=True)
    op.alter_column('job_applications', 'salary_max',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Upper bound of expected or listed pay (Numeric 12,2)',
               existing_nullable=True)
    op.alter_column('job_applications', 'salary_min',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Lower bound of expected or listed pay (Numeric 12,2)',
               existing_nullable=True)
    op.alter_column('job_applications', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Job location or remote label (not unique — many jobs share cities)',
               existing_nullable=True)
    op.alter_column('job_applications', 'job_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Employment type (JobType enum value, e.g. full_time)',
               existing_nullable=False)
    op.alter_column('job_applications', 'job_url',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Canonical job posting URL; unique when set',
               existing_nullable=True)
    op.alter_column('job_applications', 'job_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full or pasted job description text',
               existing_nullable=True)
    op.alter_column('job_applications', 'job_title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Role title (unique per company via composite constraint)',
               existing_nullable=False)
    op.alter_column('job_applications', 'company_id',
               existing_type=sa.UUID(),
               comment='Owning company (exactly one per application)',
               existing_comment='FK to companies.id; exactly one company owns this application',
               existing_nullable=False)
    op.alter_column('job_applications', 'id',
               existing_type=sa.UUID(),
               comment='Primary key',
               existing_comment='Primary key (UUID generated in the app via uuid4)',
               existing_nullable=False)
    op.alter_column('interviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was last updated (server default + ORM onupdate)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was first created (DB server default, timezone-aware)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('interviews', 'outcome',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Result of this interview only (InterviewOutcome enum value)',
               existing_nullable=True)
    op.alter_column('interviews', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Prep notes, interviewer names, takeaways, etc.',
               existing_nullable=True)
    op.alter_column('interviews', 'url_link',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Video call or portal URL for remote interviews',
               existing_nullable=True)
    op.alter_column('interviews', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Physical location or office name for onsite interviews',
               existing_nullable=True)
    op.alter_column('interviews', 'interview_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Interview format/focus (InterviewType enum value, e.g. video)',
               existing_nullable=False)
    op.alter_column('interviews', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Interview start time (timezone-aware)',
               existing_nullable=False)
    op.alter_column('interviews', 'application_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to job_applications.id; application this interview belongs to',
               existing_nullable=False)
    op.alter_column('interviews', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID generated in the app via uuid4)',
               existing_nullable=False)
    op.alter_column('contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was last updated (server default + ORM onupdate)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was first created (DB server default, timezone-aware)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contacts', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Free-form notes (last conversation, intro path, etc.)',
               existing_nullable=True)
    op.alter_column('contacts', 'linkedin_url',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Personal LinkedIn profile URL; unique when set',
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email address; unique when set',
               existing_nullable=True)
    op.alter_column('contacts', 'role',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Job title or relationship (e.g. Recruiter, Eng Manager)',
               existing_nullable=True)
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Phone number (E.164-ish room); unique when set',
               existing_nullable=True)
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Contact full name',
               existing_nullable=False)
    op.alter_column('contacts', 'company_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to companies.id; company this person works at / represents',
               existing_nullable=False)
    op.alter_column('contacts', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID generated in the app via uuid4)',
               existing_nullable=False)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was last updated (server default + ORM onupdate)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was first created (DB server default, timezone-aware)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'notes',
               existing_type=sa.TEXT(),
               comment='Free-form notes about the company',
               existing_comment='Free-form notes about the company (culture, referrals, etc.)',
               existing_nullable=True)
    op.alter_column('companies', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment='HQ or primary location',
               existing_comment='Headquarters or primary company location',
               existing_nullable=True)
    op.alter_column('companies', 'linkedin_url',
               existing_type=sa.VARCHAR(length=255),
               comment='Company LinkedIn URL',
               existing_comment='Company LinkedIn page URL; unique when set',
               existing_nullable=True)
    op.alter_column('companies', 'website',
               existing_type=sa.VARCHAR(length=255),
               comment='Company website URL',
               existing_comment='Company website URL; unique when set',
               existing_nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Company display name',
               existing_comment='Company display name (unique across the tracker)',
               existing_nullable=False)
    op.alter_column('companies', 'id',
               existing_type=sa.UUID(),
               comment='Primary key',
               existing_comment='Primary key (UUID generated in the app via uuid4)',
               existing_nullable=False)
    op.alter_column('application_status_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was last updated (server default + ORM onupdate)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('application_status_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was first created (DB server default, timezone-aware)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('application_status_history', 'notes',
               existing_type=sa.TEXT(),
               comment='Optional notes for this status change',
               existing_comment='Optional context for this status change (rejection reason, etc.)',
               existing_nullable=True)
    op.alter_column('application_status_history', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='Status recorded at this history point',
               existing_comment='Pipeline status at this history event (ApplicationStatus enum value)',
               existing_nullable=False)
    op.alter_column('application_status_history', 'application_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to job_applications.id; application this status event belongs to',
               existing_nullable=False)
    op.alter_column('application_status_history', 'id',
               existing_type=sa.UUID(),
               comment='Primary key',
               existing_comment='Primary key (UUID generated in the app via uuid4)',
               existing_nullable=False)
    # ### end Alembic commands ###
